/**
 * Camera Property Definitions
 */
import { defineSection } from '../types';
import { VIZ_COLORS } from '../../../theme/colors';
import { LINE_WIDTH } from '../../../theme/opacity';
import { CSS_HEX_COLOR_PATTERN, CSS_HEX_COLOR_PATTERN_DESCRIPTION } from '../../../utils/hexColor';
import {
  CAMERA_DISPLAY_MODES,
  FRUSTUM_COLOR_MODES,
  CAMERA_SCALE_FACTORS,
  CAMERA_MODES,
  CAMERA_PROJECTIONS,
  AUTO_ROTATE_MODES,
  HORIZON_LOCK_MODES,
  SELECTION_COLOR_MODES,
  UNDISTORTION_MODES,
} from '../../../store/types';

export const cameraSection = defineSection({
  key: 'camera',
  storeHook: 'useCameraStore',
  properties: [
    // Display
    {
      key: 'show',
      storeKey: 'showCameras',
      type: 'boolean',
      default: true,
      persist: true,
      description: 'Show/hide camera frustums',
    },
    {
      key: 'displayMode',
      storeKey: 'cameraDisplayMode',
      type: 'enum',
      enumValues: CAMERA_DISPLAY_MODES,
      default: 'frustum',
      persist: true,
      description: 'frustum | arrow | imageplane',
    },
    {
      key: 'scaleFactor',
      storeKey: 'cameraScaleFactor',
      type: 'enum',
      enumValues: CAMERA_SCALE_FACTORS,
      default: '1',
      persist: true,
      description: '0.1 | 1 | 10',
    },
    {
      key: 'scale',
      storeKey: 'cameraScale',
      type: 'number',
      min: 0.01,
      max: 10,
      default: 0.6,
      persist: true,
      description: 'Frustum size multiplier (0.01 - 10)',
    },
    {
      key: 'frustumColorMode',
      type: 'enum',
      enumValues: FRUSTUM_COLOR_MODES,
      default: 'single',
      persist: true,
      description: 'single | byCamera | byRigFrame | splatPsnr | splatSsim',
    },
    {
      key: 'frustumSingleColor',
      type: 'string',
      pattern: CSS_HEX_COLOR_PATTERN,
      patternDesc: CSS_HEX_COLOR_PATTERN_DESCRIPTION,
      default: VIZ_COLORS.frustum.default,
      persist: true,
      description: 'Hex color for single frustum color mode',
    },
    {
      key: 'frustumStandbyOpacity',
      type: 'number',
      min: 0,
      max: 1,
      default: 0.9,
      persist: true,
      description: 'Frustum opacity when no camera is selected (0 - 1)',
    },
    {
      key: 'frustumLineWidth',
      type: 'number',
      min: 1,
      max: 6,
      default: LINE_WIDTH.frustum,
      persist: true,
      description: 'Frustum wireframe line width (1 - 6)',
    },
    {
      key: 'unselectedOpacity',
      storeKey: 'unselectedCameraOpacity',
      type: 'number',
      min: 0.1,
      max: 0.6,
      default: 0.5,
      persist: true,
      description: 'Opacity of non-selected cameras (0.1 - 0.6)',
    },
    // Navigation
    {
      key: 'mode',
      storeKey: 'cameraMode',
      type: 'enum',
      enumValues: CAMERA_MODES,
      default: 'orbit',
      persist: true,
      description: 'orbit | fly',
    },
    {
      key: 'projection',
      storeKey: 'cameraProjection',
      type: 'enum',
      enumValues: CAMERA_PROJECTIONS,
      default: 'perspective',
      persist: true,
      description: 'perspective | orthographic',
    },
    {
      key: 'fov',
      storeKey: 'cameraFov',
      type: 'number',
      min: 10,
      max: 120,
      default: 60,
      persist: true,
      description: 'Field of view (10 - 120)',
    },
    {
      key: 'horizonLock',
      type: 'enum',
      enumValues: HORIZON_LOCK_MODES,
      default: 'off',
      persist: true,
      description: 'off | on | flip',
    },
    {
      key: 'autoRotateMode',
      type: 'enum',
      enumValues: AUTO_ROTATE_MODES,
      default: 'off',
      persist: true,
      description: 'off | cw | ccw',
    },
    {
      key: 'autoRotateSpeed',
      type: 'number',
      min: 0.1,
      max: 2,
      default: 0.5,
      persist: true,
      description: 'Auto-orbit speed in radians per second (0.1 - 2)',
    },
    {
      key: 'flySpeed',
      type: 'number',
      min: 0.1,
      max: 50,
      default: 2.5,
      persist: true,
      description: 'Flying speed (0.1 - 50)',
    },
    {
      key: 'flyTransitionDuration',
      type: 'number',
      min: 0,
      max: 2000,
      default: 600,
      persist: true,
      description: 'Fly-to animation duration in ms (0 = instant)',
    },
    {
      key: 'pointerLock',
      type: 'boolean',
      default: true,
      persist: true,
    },
    // Selection
    {
      key: 'showSelectionHighlight',
      type: 'boolean',
      default: true,
      persist: true,
      description: 'Show/hide selection point highlighting',
    },
    {
      key: 'selectionColorMode',
      type: 'enum',
      enumValues: SELECTION_COLOR_MODES,
      default: 'rainbow',
      persist: true,
      description: 'static | blink | rainbow',
    },
    {
      key: 'selectionColor',
      type: 'string',
      pattern: CSS_HEX_COLOR_PATTERN,
      patternDesc: CSS_HEX_COLOR_PATTERN_DESCRIPTION,
      default: '#00ff00',
      persist: true,
      description: 'Hex color for static selection mode',
    },
    {
      key: 'selectionAnimationSpeed',
      type: 'number',
      min: 0.1,
      max: 10,
      default: 2,
      persist: true,
    },
    // Selection planes (opacity of selected camera's image plane)
    // Default 1.0 ensures depthWrite: true so image properly occludes frustums behind it
    {
      key: 'selectionPlaneOpacity',
      type: 'number',
      min: 0,
      max: 1,
      default: 1.0,
      persist: true,
    },
    // Undistortion
    {
      key: 'undistortionEnabled',
      type: 'boolean',
      default: false,
      persist: true,
      description: 'Apply lens undistortion to frustum images',
    },
    {
      key: 'undistortionMode',
      type: 'enum',
      enumValues: UNDISTORTION_MODES,
      default: 'fullFrame',
      persist: true,
      description: 'cropped | fullFrame',
    },
    // Auto FOV
    {
      key: 'autoFovEnabled',
      type: 'boolean',
      default: true,
      persist: true,
      description: 'Auto-adjust FOV when flying to cameras',
    },
    // Transient properties (not persisted)
    {
      key: 'flyToImageId',
      type: 'number',
      default: 0,
      persist: false,
      transient: true,
    },
    {
      key: 'selectedImageId',
      type: 'number',
      default: 0,
      persist: false,
      transient: true,
    },
  ],
});
